version: "3.9"
services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=shopify-challenge-db
            - PGADMIN_LISTEN_PORT=5432
        user: root
        volumes:
            - postgres:/bar/lib/postgressql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    cloudstorage:
        image: fsouza/fake-gcs-server
        tty: true
        stdin_open: true
        privileged: true
        security_opt:
            - seccomp:unconfined
        volumes:
            - ./gcs-example-base:/data
            - ./cloudstorage:/storage
        ports:
            - "4443:4443"
        command: -scheme http --public-host localhost:4443
        # test availability curl http://localhost:4443/storage/v1/b

    web:
        build: .
        ports:
            - "8080:8080"
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - JWT_SECRET=${JWT_SECRET}
            - IS_DEBUG=${IS_DEBUG}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
            - CLOUD_STORAGE_HOST=cloudstorage
            - IS_CONTAINER=true
        depends_on:
            db:
                condition: service_healthy

    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
        volumes:
            - ./pgadmin/data:/root/.pgadmin
            - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
        ports:
            - "80:80"
        entrypoint:
            - "/bin/sh"
            - "-c"
            - "/bin/echo 'db:5432:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
        depends_on: 
            - db
        restart: unless-stopped
        profiles: ["dev"]

volumes:
    postgres:
        name: postgres-data